// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWekutihTwiT0G6R13pQyVoIn_jzWvb50',
    appId: '1:989424202430:web:9f3d6d64d9db632387a4ef',
    messagingSenderId: '989424202430',
    projectId: 'employee-management-b4100',
    authDomain: 'employee-management-b4100.firebaseapp.com',
    storageBucket: 'employee-management-b4100.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDybaKpWDIwbI-tCuymZyffo1zsSvgmeuU',
    appId: '1:989424202430:android:c1f8c2b7270e946087a4ef',
    messagingSenderId: '989424202430',
    projectId: 'employee-management-b4100',
    storageBucket: 'employee-management-b4100.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB7j5jqiIFBM-ih8w4n8RqjCS0-Dk8D88',
    appId: '1:989424202430:ios:aae0fb3c24860d0987a4ef',
    messagingSenderId: '989424202430',
    projectId: 'employee-management-b4100',
    storageBucket: 'employee-management-b4100.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB7j5jqiIFBM-ih8w4n8RqjCS0-Dk8D88',
    appId: '1:989424202430:ios:aae0fb3c24860d0987a4ef',
    messagingSenderId: '989424202430',
    projectId: 'employee-management-b4100',
    storageBucket: 'employee-management-b4100.firebasestorage.app',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCWekutihTwiT0G6R13pQyVoIn_jzWvb50',
    appId: '1:989424202430:web:d412eff0b96f70af87a4ef',
    messagingSenderId: '989424202430',
    projectId: 'employee-management-b4100',
    authDomain: 'employee-management-b4100.firebaseapp.com',
    storageBucket: 'employee-management-b4100.firebasestorage.app',
  );
}
